include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "**.gr.dart"

linter:
  rules:
    avoid_relative_lib_imports: true
    discarded_futures: true
    cascade_invocations: true
    unawaited_futures: true
